name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: melvinlarsson/myrepo:1.1
      credentials:
        username: ${{ vars.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      volumes:
        - .:/src

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Build
        run: make
